/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import logica.Accesorio;
import logica.Avatar;
import logica.Boca;

/**
 *
 * @author Caribe
 */
public class pnCanvas extends javax.swing.JPanel implements Observer {

    private Ventana ventana;
    private Graphics2D graf;
    private Avatar currentAvatar;
    private BufferedImage image;

    private BufferedImage image1;
    private BufferedImage image2;
    private BufferedImage image3;
    private BufferedImage image4;
    private BufferedImage image5;

    private BufferedImage imageCabello;
    private BufferedImage imageOjos;
    private BufferedImage imageBoca;
    private BufferedImage imageCuerpo;
    private BufferedImage imagePies;

    public pnCanvas(Ventana vent) {
        initComponents();
        ventana = vent;

        currentAvatar = new Avatar();

        URL resource = getClass().getResource("/img/body/EmptyBody.PNG");
        try {
            image = ImageIO.read(resource);
            Accesorio s = new Boca();
            s.setX(10);
        } catch (IOException e) {
            e.printStackTrace();
        }

        // SOLO ES PARA SABER LAS POSICIONES  1,2,3,4
        URL resource1 = getClass().getResource("/img/peinados/hair3.png");
        try {
            image1 = ImageIO.read(resource1);
        } catch (IOException e) {
            e.printStackTrace();
        }
        URL resource2 = getClass().getResource("/img/eyes/eyes1.PNG");
        try {
            image2 = ImageIO.read(resource2);
        } catch (IOException e) {
            e.printStackTrace();
        }
        URL resource3 = getClass().getResource("/img/mouths/mouth4.PNG");
        try {
            image3 = ImageIO.read(resource3);
        } catch (IOException e) {
            e.printStackTrace();
        }
        URL resource4 = getClass().getResource("/img/body/body5.png");
        try {
            image4 = ImageIO.read(resource4);
        } catch (IOException e) {
            e.printStackTrace();
        }
        URL resource5 = getClass().getResource("/img/bottoms/bottom1.png");
        try {
            image5 = ImageIO.read(resource5);
        } catch (IOException e) {
            e.printStackTrace();
        }
    } // 328 92

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        graf = (Graphics2D) g;

        graf.drawImage(image, 45, 15, this);

        if (currentAvatar != null) {
            if (currentAvatar.getCabello() != null) {
                //CABELLO  482   343
                graf.drawImage(image1, 48, 10, 150, 100, this);
            }

            if (currentAvatar.getOjos() != null) {
                //OJOSm   272  140
                graf.drawImage(image2, 87, 80, 70, 35, this);
            }

            if (currentAvatar.getBoca() != null) {
                //BOCA 151  65
                graf.drawImage(image3, 105, 133, 30, 15, this);
            }

            if (currentAvatar.getPies() != null) {
                //PIES
                graf.drawImage(image5, 71, 200, 114, 23, this);
            }

            if (currentAvatar.getCuerpo() != null) {
                //CUERPO 
                graf.drawImage(image4, 55, 137, 137, 74, this);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {
        this.repaint();
        System.out.println("Hey, me han invocado");
    }

    public Avatar getCurrentAvatar() {
        return currentAvatar;
    }

    public void setCurrentAvatar(Avatar currentAvatar) {
        this.currentAvatar = currentAvatar;
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
